export let exercises = [
    { name: 'Ab wheel', category: 'Abs'},
    { name: 'Bench press', category: 'Chest'},
    { name: 'Bentover row', category: 'Back'},
    { name: 'Bicep curl', category: 'Arms'},
    { name: 'Cable crunch', category: 'Abs'},
    { name: 'Calf raise', category: 'Legs'},
    { name: 'Chest dip', category: 'Chest'},
    { name: 'Chest fly', category: 'Chest'},
    { name: 'Crunch', category: 'Abs'},
    { name: 'Deadlift', category: 'Back'},
    { name: 'Decline bench press', category: 'Chest'},
    { name: 'Decline chest fly', category: 'Chest'},
    { name: 'Decline crunch', category: 'Abs'},
    { name: 'Front raise', category: 'Shoulders'},
    { name: 'Incline bench press', category: 'Chest'},
    { name: 'Incline chest fly', category: 'Chest'},
    { name: 'Lat pulldown', category: 'Back'},
    { name: 'Lateral raise', category: 'Shoulders'},
    { name: 'Leg curl', category: 'Legs'},
    { name: 'Leg extention', category: 'Legs'},
    { name: 'Leg press', category: 'Legs'},
    { name: 'Leg raise', category: 'Abs'},
    { name: 'Overhead press', category: 'Shoulders'},
    { name: 'Overhead tricep extension', category: 'Arms'},
    { name: 'Pull up', category: 'Back'},
    { name: 'Push up', category: 'Back'},
    { name: 'Seated row', category: 'Back'},
    { name: 'Shrug', category: 'Shoulders'},
    { name: 'Sit up', category: 'Abs'},
    { name: 'Squat', category: 'Legs'},
    { name: 'Tricep dip', category: 'Arms'},
    { name: 'Tricep pushdown', category: 'Arms'}
];